spring.application.name=api-gateway
server.port=9191

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Gateway routes - Spring Cloud Gateway Server MVC
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.server.webmvc.routes[1].id=new-connection-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://NEW-CONNECTION-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/connections/**

spring.cloud.gateway.server.webmvc.routes[2].id=metering-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://METERING-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/metering/**

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=read-only

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.org.springframework.cloud.netflix.eureka=DEBUG